### ISSUE TITLE
Unhandled exception in unit ban list

### ISSUE THREAD

**Issue by GoldenGnu** [DCS-BR-Tools/briefing-room-for-dcs#1056] opened 2024-12-17 21:09 UTC
### Brief Description: 
Start > Full Generator > Unit Ban List

I get an unhandled exception, as follow:
 ```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at BriefingRoom4DCS.Data.DBEntryJSONUnit.GetDBEntryInfo() in D:\a\briefing-room-for-dcs\briefing-room-for-dcs\src\BriefingRoom\Data\JSON\DBEntryJSONUnit.cs:line 47
   at BriefingRoom4DCS.BriefingRoom.<>c.<GetDatabaseEntriesInfo>b__31_32(DBEntryJSONUnit x) in D:\a\briefing-room-for-dcs\briefing-room-for-dcs\src\BriefingRoom\BriefingRoom.cs:line 152
   at System.Linq.Enumerable.ArrayWhereSelectIterator`2.ToArray(ReadOnlySpan`1 source, Func`2 predicate, Func`2 selector)
   at System.Linq.Enumerable.ArrayWhereSelectIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BriefingRoom4DCS.GUI.Common.Pages.FullBuilder.<BuildRenderTree>b__0_6(RenderTreeBuilder __builder2) in D:\a\briefing-room-for-dcs\briefing-room-for-dcs\src\CommonGUI\Pages\FullBuilder.razor:line 701
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at Microsoft.AspNetCore.Components.CascadingValue`1.Render(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.IpcSender.<>c__DisplayClass12_0.<NotifyUnhandledException>b__1()
   at Microsoft.AspNetCore.Components.WebView.WindowsForms.WindowsFormsDispatcher.InvokeAsync(Action workItem)
   at Microsoft.AspNetCore.Components.WebView.WindowsForms.WindowsFormsDispatcher.<>c.<.cctor>b__8_0(Exception exception)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
Desktop
    Assembly Version: 1.0.0.0
    Location: 
----------------------------------------
System.Runtime
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Windows.Forms
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Private.Windows.Core
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Collections.Specialized
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Threading
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Collections
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
Microsoft.Extensions.DependencyInjection.Abstractions
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
Microsoft.AspNetCore.Components.WebView.WindowsForms
    Assembly Version: 1.0.0.0
    Location: 
----------------------------------------
Microsoft.AspNetCore.Components.WebView
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
Blazored.LocalStorage
    Assembly Version: 1.0.0.0
    Location: 
----------------------------------------
BriefingRoom
    Assembly Version: 1.0.0.0
    Location: 
----------------------------------------
Microsoft.Extensions.DependencyInjection
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.ComponentModel
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.ObjectModel
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
Microsoft.AspNetCore.Components.Web
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
Microsoft.AspNetCore.Components
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Drawing.Common
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Threading.Thread
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Location: 
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
Microsoft.Extensions.Logging
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
Microsoft.JSInterop
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
Microsoft.Extensions.Options
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Linq
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly Version: 1.0.2792.45
    Location: 
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly Version: 1.0.2792.45
    Location: 
----------------------------------------
mscorlib
    Assembly Version: 4.0.0.0
    Location: 
----------------------------------------
Microsoft.Extensions.FileProviders.Abstractions
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Private.Uri
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Drawing
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
Microsoft.Extensions.FileProviders.Physical
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
Microsoft.Extensions.Primitives
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
Microsoft.Extensions.FileProviders.Composite
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Location: 
----------------------------------------
System.Threading.Tasks
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Runtime.Loader
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Memory
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
Microsoft.Extensions.FileProviders.Embedded
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Xml.XDocument
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Private.Xml.Linq
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Private.Xml
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Text.Json
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Text.Encodings.Web
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Runtime.Intrinsics
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Collections.Immutable
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.IO.Pipelines
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Linq.Expressions
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Location: 
----------------------------------------
CommonGUI
    Assembly Version: 1.0.0.0
    Location: 
----------------------------------------
System.Console
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Location: 
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 8.1.0.0
    Location: 
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Data.Common
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
LuaTableSerializer
    Assembly Version: 1.0.0.0
    Location: 
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
Microsoft.AspNetCore.Components.Forms
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
Blazored.Typeahead
    Assembly Version: 1.0.0.0
    Location: 
----------------------------------------
System.ComponentModel.Annotations
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.IO.Compression
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------
System.IO.MemoryMappedFiles
    Assembly Version: 9.0.0.0
    Location: 
----------------------------------------

************** JIT Debugging **************
```

### Expected: 
No unhandled exceptions

#### Mission and Template Zip:

This happen with the default template

**Comment by john681611** [comment] 2024-12-17 23:35
Thanks for the report I'll look into it

**Comment by john681611** [comment] 2024-12-18 21:35
Caused by a unit that has been removed from the editor (but is still in our data) breaking some code. Will be in the next release.

**Closed** 2024-12-18 22:51 UTC
Labels: bug
